### ISSUE TITLE
make sure we delete outdated html files from the server 

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#103]
the soc people just reported a bug after they found that an html page that was not part of the html output anymore had not been removed from the server. if possible, we should try to avoid that issue in the future.

**Comment by tomschr** [comment]
Not entirely sure, but for me it looks like the 'rsync' command needs one of the `--delete` / `--delete-{after,before}` options.
See https://linux.die.net/man/1/rsync for details.

**Comment by svenseeberg** [comment]
Totally valid bug report and also the solution seems valid to me.

**Comment by sknorr** [comment]
Eli has fixed this, though triggering #195 in the process (that however is extremely easy to fix).
