### ISSUE TITLE
docserv-createconfig writes too many FIXME values

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#117]
[slightly rambling issue, might need to split into two at some point.]

* Right now, docserv-createconfig creates "draft" files that include lots of FIXMEs, including for stuff like the product name. Ideally, we'd be getting the count of written FIXMEs down.

---

(Edit by Toms: Split this issue in two separate tasks. This one and #120 )

**Comment by tomschr** [comment]
Yes, good idea! Actually, I wasn't really satisfied with the output too. :wink:
