### ISSUE TITLE
docserv-createconfig: what is the version for develop or master branch

### ISSUE THREAD

**Issue by eliroca** [openSUSE/docserv#122]
With #121 I've added a method that adds in the version, taking it from the branch name. With branches like master and develop, we don't have a fix version number(currently SLE 15).

We could just add "develop" for develop branch as version -> `<version>develop</version>`
Any other ideas/thoughts?

**Comment by sknorr** [comment]
There are some things that need to be set by hand. This is one of them. docserv-createconfig is supposed to make your life easier if you have to configure a new product but it can't feasibly do all the work.
