### ISSUE TITLE
createconfig: XMLSyntaxError when parsing book_cloud_suppl.xml

### ISSUE THREAD

**Issue by eliroca** [openSUSE/docserv#138]
When parsing `book_cloud_suppl.xml`  from maintenance/cloud_5  in python like this:
`etree.parse(path/to/book_cloud_suppl.xml)`

The following Error comes out:
`lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 96, column 27 (book_cloud_suppl.xml, line 96)`

**Comment by sknorr** [comment]
@tomschr / @eliroca What is the reason for this issue? Do we need system entities from somewhere in that case?

**Comment by tomschr** [comment]
> @tomschr / @eliroca What is the reason for this issue?

Well, as far as I can see, the script can't parse the XML file because of the entity. We need to fix this.


> Do we need system entities from somewhere in that case?

Yes, seems so. The `book_cloud_suppl.xml` file is still Novdoc (DocBook 4) and uses the DTD. It contains references to some system entities (like `&nbsp;`). To load the DTD and resolve the entities, this code worked for me:


```python
parser = etree.XMLParser(resolve_entities=True, dtd_validation=False, load_dtd=True)
root = etree.parse("xml/book_cloud_suppl.xml", parser=parser)
# ...
```

**Comment by eliroca** [comment]
Thanks @tomschr! Seems to work fine with your `parser`.

Although I did get this Error when parsing `ha_docupdates.xml` from `master` branch in SLE-HA:
`lxml.etree.XMLSyntaxError: ID sec.ha.docupdates.sle12_sp2_maint_2 already defined, line 95, column 53`
All other branches were fine.
I guess we can ignore this, as master is outdated anyways..

**Comment by eliroca** [comment]
I suggest we close this issue, as we will no longer be parsing XML to get the subdeliverables.
