### ISSUE TITLE
translations work differently from original language and python does not know yet

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#17]
to make it simpler for authors to configure translations, translations are essentially a black list v/ the default \<language/\>. the docserv python script does not know that yet and hence will not actually build translations (slightly different structure).

there are two possible avenues here:

1. run an xslt step over the contents of \<language default="0"/\> and make the content conform to docserv's expectations before it touches the file

2. make the docserv script understand the black list thing.

i would almost guess that (1) is easier. we could perhaps even do away with some other complications that the docserv script needs to know nothing about... tb determined.

**Comment by svenseeberg** [comment]
Can I get dish no 1 please?

**Comment by sknorr** [comment]
I'll try.

**Comment by svenseeberg** [comment]
Thanks!
