### ISSUE TITLE
docserv2: shows KeyError when trying to build to undefined target

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#178]
if your INI has no target `name = test1000` but you're creating a build instruction via API for target server `test1000`, you get a KeyError. this should probably go into a try/catch block.

**Comment by tomschr** [comment]
Just for the sake of completeness: if you can define a default value, you can avoid KeyErrors by using the `dictinst.get()` method.

**Comment by sknorr** [comment]
I guess a default value is not helpful in this case. If you have two remotes named `internal`/`external` (which incidentally, we do) and then make an API call using the typo'd version `imternal`, it wouldn't be helpful if randomly, the `external` target would be selected. :)
