### ISSUE TITLE
RPM: Move /etc -> /usr/etc

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docserv#221]
## Situation

There was a proposal from Torsten Kukuck about moving `/etc/` files to `/usr/etc`. It's very likely that this affects the RPM of docserv too.

## Expected Solution

Although the docserv package is kind of "hidden" from Factory ATM, we should nevertheless adhere to proposed recommendations. IMHO, we should also consider to submit the package to Factory at some point in time. If we do that, rpmlint checks will raise warnings or even errors if we don't conform to this new "spec".

* [ ] Check if this is neccessary
* [ ] If yes, move files from `/etc/docserv` files to `/usr/etc/docserv`
* [ ] Adjust `*.spec` file
* [ ] Adjust `docserv.ini` to point to the correct paths.

## References

* https://en.opensuse.org/openSUSE:Packaging_UsrEtc
* https://lists.opensuse.org/opensuse-packaging/2019-09/msg00010.html
* https://mailman.suse.de/mlarch/SuSE/research/2019/research.2019.07/msg00378.html

**Comment by sknorr** [comment]
We are not affected. Everything under /etc is entirely created by the admin.

https://build.opensuse.org/package/view_file/Documentation:Tools/docserv/docserv.spec?expand=1
