### ISSUE TITLE
Selecting Language does not work in Chromium

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docserv#222]
Reported by @fsundermeyer 

Used browser: Vivaldi & Chromium

1. Open the HTML documentation on docserv.
2. Select the language from the pop-up menu

=> It won't change the language.

On Toms computer (Firefox Version 60.8.0esr) it worked.

Probably the JavaScript file needs to be adapted.

**Comment by fsundermeyer** [comment]
Should be fixed with https://github.com/openSUSE/docserv/pull/224
