### ISSUE TITLE
Doc set is not preselected

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docserv#223]
Browsing to http://&lt;SERVER&gt;/en-us/#sled displays the same result as http://&lt;SERVER&gt;/en-us/.

It needs to show the SLED versions available in the "2. Select Version" field as if SLED was selected by the user.

Why is this important:
We do not have any index page for /en-us/sled/ and therefore need to redirect any access to this page to /en-us/#sled. This redirect needs to show the manuals that are available.

**Comment by sknorr** [comment]
Hm, my idea was slightly different: for each product, we already define a default docset and that is where I would have placed the redirect to. At least in the ideal world in which docserv2 can build own htaccess files

**Comment by fsundermeyer** [comment]
We are talking about two different things here:

* http:/documentation.suse.com/#sles
* http:/documentation.suse.com/sles

The first one is what you get when selecting an entry from the "Select Product Box". Therefore it must not be redirected. Whatsmore, it is in your browser history.

The second one should work as a shortcut for the current product. If we can build the respective redirects in .htaccess automatically, the better.

**Comment by sknorr** [comment]
Fixed in a1a232ae58.
