### ISSUE TITLE
Documents added with <internal="ref"...> are not shown in overview pages

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docserv#225]
See http://10.160.64.170/soc/9/

The docs that have been added with

    <internal>
      <ref product="sbp" docset="all" dc="DC-SBP-CloudLS-master"/>
      <ref product="sbp" docset="all" dc="DC-SBP-publiccloudinfra"/>
      <ref product="sbp" docset="all" dc="DC-SBP-Spectre-Meltdown-L1TF"/>
    </internal>

are not shown in said page. However, it works for SUMA.

**Comment by sknorr** [comment]
Odd. It does work for SOC 8 too.

I am wondering if this was just a build timing issue -- i.e. if SOC 9 was rebuilt before or while rebuilding the SBP, I guess this might happen. The reason for that is that we only link documents that have already been built and if the SBP hadn't been built yet, there would be nothing to link to.

Could you try rebuilding SOC 9 again and see if this continues to be an issue?

Though even if that fixes it, please leave this issue open anyway, we need to detect these dependencies while building the web stuff and rebuild more than just the current product's page.

**Comment by fsundermeyer** [comment]
Looks like this happens when you put external links into a category. This is the only difference between SOC 9 and SOC 8.

Also put external links for SUMA into categories and the internal links are gone.

**Comment by sknorr** [comment]
Fixed.
