### ISSUE TITLE
Breadcrumbs should terminate with the currently viewed doc

### ISSUE THREAD

**Issue by dmpop** [openSUSE/docserv#226]
When the user selects, say, _SUSE OpenStack Cloud 9_, the breadcrumb should be **Home > Product Documentation > SUSE OpenStack Cloud 9** and not **Home > Product Documentation**.

**Comment by sknorr** [comment]
The breadcrumbs stuff is not part of this repo. Please report against docserv-config. (But I do agree, this needs to be fixed.)
