### ISSUE TITLE
Unsupported product link in odd location

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docserv#228]
The "View Unsupported Products instead" is listed at the bottom of the selection boxes and has a lot of whitespace between the box and the link. It is therefore hard to find.

The "View Supported Products instead." link is on top of the selection boxes and clearly visible.

**Comment by sknorr** [comment]
This is fixed on the production site.

Notably, this was only a template issue on documentation.suse.com, so this issue should have been reported in https://github.com/susedoc/documentation.suse.com-issues.
