### ISSUE TITLE
Categorize <internal> docs

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docserv#231]
ATM Docs added within <internal> cannot be put into a category. Would be nice to be able to do that.

Also see issue #225

**Comment by fsundermeyer** [comment]
From @chabowski 

At the bottom of the product pages there are several documents such as e.g. Release Notes and Best Practices. Can we categorize that? It looks quite unclear currently.

I think Release notes are so important that they deserve their own category.

And the other docs could be listed under a category "Additional Documents" or, if there are many best practices, a category "Best Practices".

**Comment by sknorr** [comment]
Categorization has actually been possible since the introduction of internal references.
