### ISSUE TITLE
Version-Specific addendum to <desc> needed

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docserv#234]
It would be good to be able to be able to provide some version-specific, optional text in addition to the general product description &lt;desc&gt;.

This is needed for e.g. SUMA for Retail. It was a stand-alone product since version 3.1 and has become a part of SUMA since then. Howeve, since SUMA for Retail is listed as a separate product, wel also need to list versions 3.2 and 4.0 under this product. Would be good to have the possibility to add something like "Starting with version 3.2, SUMA for retail is no longer a stand-alone product,...."
Same is true for the HA GEO extension.

**Comment by sknorr** [comment]
fixed in 2ed6074
