### ISSUE TITLE
Create alias for d.s.c variants

### ISSUE THREAD

**Issue by asettle** [openSUSE/docserv#235]
Request from an internal SUSE employee to create two new aliases for doc.suse.com and docs.suse.com and redirect them to documentation.suse.com

Motivation:

1. for people who remember the domain wrong
1. to give a way to reach the site with less typing needed

**Comment by sknorr** [comment]
This doesn't really belong in this repo but I totally support this idea. Frank has self-assigned this, so leaving this open.

**Comment by sknorr** [comment]
Created a RIO ticket, opened a replacement bug at https://github.com/SUSEdoc/documentation.suse.com-issues/issues/17

**Comment by asettle** [comment]
Gracias
