### ISSUE TITLE
Redirects are to a single location - google search problem

### ISSUE THREAD

**Issue by asettle** [openSUSE/docserv#236]
When searching Google for something specific within SUSE docs (IE: "suse barclamp") your first respose is this: 

See:
![barclamp-example](https://user-images.githubusercontent.com/1987994/65593164-d7772700-df87-11e9-80aa-7882e0f9a933.png)

But if you click on any of these individual links, they automatically redirect back to https://documentation.suse.com/soc/9/#redirectmsg

![redirect-example](https://user-images.githubusercontent.com/1987994/65593231-f4135f00-df87-11e9-84bc-2e6a822c1766.png)

This is going to provide a bad user experience in the long-term as users will be unable to find pages they have book marked, and the search engine will "prove" to be useless, causing confusion.

Redirects take time and effort, and it's a lot of content mapping since the redirects changed locations and names. I suggest a pop-up banner is added to this page: https://documentation.suse.com/soc/9/#redirectmsg when it is specifically accessed with the redirect hash to say something like "Apologies for the misdirection at this time, we are working through creating a new and improved website. This may mean that your links are broken and redirects directly to the home page. We apologise for this inconvenience and please be patient with us." Or something to that effect.

**Comment by sknorr** [comment]
So,

* This isn't really the right repo for this report, because this is a template issue. 
* There is a message saying pretty much what you want it to say but you don't see it by default.

Opened a replacement issue here:
https://github.com/SUSEdoc/documentation.suse.com-issues/issues/11
