### ISSUE TITLE
rsync is syncing .git files

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docserv#237]
Use the `--cvs-exclude` flag with rsync to prevent this.

**Comment by tomschr** [comment]
I've grepped through the source tree and the most relevant lines are these:

* file [`src/docserv/bih.py`, line 119](https://github.com/openSUSE/docserv/blob/master/src/docserv/bih.py#L119)
* file [`src/docserv/bih.py`, line 163](https://github.com/openSUSE/docserv/blob/master/src/docserv/bih.py#L163)
* file [`src/docserv/bih.py`, line 170](https://github.com/openSUSE/docserv/blob/master/src/docserv/bih.py#L170)
* file [`src/docserv/deliverable.py`, line 198](https://github.com/openSUSE/docserv/blob/master/src/docserv/deliverable.py#L198)

I *think* this option could be added without problems.

**Comment by sknorr** [comment]
The only line where it´s relevant is file src/docserv/bih.py, line 170, feel free to add there (I took the liiberty of amending Toms's comment to highlight that.

**Comment by tomschr** [comment]
Thanks Stefan, see PR #239

**Comment by sknorr** [comment]
fixed with https://github.com/openSUSE/docserv/commit/b61c28d06b917e6df9ff7683abe4ed083500f870
