### ISSUE TITLE
SEO: Using a sitemap?

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docserv#238]
## Situation

** Disclaimer: If we already have something similar, close this issue **

Compared to the past, SEO has been improved a lot. However, I'm not sure if we currently use a Google sitemap to further help search engines.

## Expected Benefits

* The obvious part: help search engines to improve search
* Make our pages more relevant to our readers
* Advocate SUSE's documentation
* With a sitemap, it "opens" the Google Search Console (GSC) which helps to extract statistics

## Proposed Solution

We need to automatically (re)create the sitemap, either by docserv itself or by an outside process (cron job, daemon, whatever).

## Further Information

* https://support.google.com/webmasters/answer/183668?hl=en
* https://ahrefs.com/blog/how-to-create-a-sitemap/

**Comment by fsundermeyer** [comment]
Merged inti issue #229
