### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docserv#27]
## Problem

The logging level is currently hard coded to [`DEBUG`](https://github.com/openSUSE/docserv/blob/master/bin/docserv#L810).

## Expected behaviour

The logging level should be configurable, probably through an option in the config file. This is very useful to see what's going on in the script (and to reduce or extend the logging information).

**Comment by svenseeberg** [comment]
Looky look here: https://github.com/openSUSE/docserv/blob/master/config/docserv.ini#L8
