### ISSUE TITLE
Parsing bigfiles

### ISSUE THREAD

**Issue by svenseeberg** [openSUSE/docserv#29]
When loading a docbook XML bigfile with xml.etree.ElementTree.parse(), I get the following object:

```
>>> from xml.etree import ElementTree
>>> tree = ElementTree.parse(bigfile_path)
>>> xml_root =tree.getroot()
>>> print(xml_root)
<Element '{http://docbook.org/ns/docbook}book' at 0x7f015a1393b8>
```

It seems I am not capable of using the find() method to extract the book/set title from the tree. @sknorr @tomschr what is the correct XPath expression that is working with Python3 xml? Some of the basic expressions I tried to use:

```
>>> print(xml_root.findall('.//title'))
[]
>>> print(xml_root.findall('{http://docbook.org/ns/docbook#}title'))
[]
>>> print(xml_root.findall('.//{http://docbook.org/ns/docbook#}title'))
[]
>>> print(xml_root.findall('.//title', {'': '{http://docbook.org/ns/docbook#}'}))
[]
```

**Comment by sknorr** [comment]
I never worked with namespaces in LXML, but you can at least pretty easily make sure that namespaces do not interfere, using the local-name() function:

```
//*[local-name(.) = 'title']
```

In all the cases where you don't have a root ID, you should be 98% golden if you do this, actually:

```
//*[local-name(.) = 'title'][1]
```

I'd recommend using local-name() given that we still have DocBook 4 anyway which is not namespaced.

**Comment by tomschr** [comment]
Heretical question: why not migrate our old stuff from version 4 to DocBook 5...? :running_man:

**Comment by svenseeberg** [comment]
Thanks for your help. The following works now:
```
>>> from xml.etree import ElementTree
>>> tree = ElementTree.parse("/home/sven/Code/doc-sle/build/.tmp/book.sle.admin_bigfile.xml")
>>> xml_root =tree.getroot()
>>> xml_root.find(".//x:title", namespaces={'x': 'http://docbook.org/ns/docbook'})
<Element '{http://docbook.org/ns/docbook}title' at 0x7f7b143faef8>
>>> tree.find(".//x:title", namespaces={'x': 'http://docbook.org/ns/docbook'})
<Element '{http://docbook.org/ns/docbook}title' at 0x7f7b143faef8>
```
