### ISSUE TITLE
opensuse/microos-docserv container image: hostname: command not found

### ISSUE THREAD

**Issue by mikelpr** [openSUSE/docserv#305]
trying to run the latest tagged image from registry.opensuse.org/opensuse/microos-docserv:latest, I get:

```
/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/usr/local/bin/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/usr/local/bin/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/usr/local/bin/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/usr/local/bin/docker-entrypoint.sh: Launching /docker-entrypoint.d/70-create-self-signed-certificates.sh
/docker-entrypoint.d/70-create-self-signed-certificates.sh: line 18: hostname: command not found
```

LABEL org.opensuse.reference="registry.opensuse.org/opensuse/microos-docserv:20240320-6.1885"

I've seen there are [newer builds](https://build.opensuse.org/projects/openSUSE:Containers:Tumbleweed/packages/microos-docserv-image.20240812121643/files/Dockerfile), but the one on the registry tops out at 20240320. and even then Dockerfile appears unchanged for 10 months. (maybe `hostname` was dropped from the nginx image? idk)

**Comment by tomschr** [comment]
Hi @mikelpr thanks for your message.

However, I'm not sure how your report is related to this project. This project is about building documentation. Yes, it uses containers, but very specific ones.

If you have problems with a specific container, maybe you file a bug in their respective repository?

**Comment by mikelpr** [comment]
@tomschr sorry Tom couldn't find the repo for it so I thought it was handled here, I know 
 https://github.com/openSUSE/container-images but it's not there.

to be clear, I'm talking about the container for docserv itself, not about containers that docserv uses.

**Comment by tomschr** [comment]
@mikelpr No problem. :slightly_smiling_face: 

Well, this is the wrong one. Not sure where you get that, but our standard container is on OBS:
https://build.opensuse.org/package/show/Documentation:Containers/daps-toolchain

However, this is the usual container we use. If you really want to use a different one, you need to set it in the INI config file:

https://github.com/openSUSE/docserv/blob/main/config/my-site.ini#L75

**Comment by mikelpr** [comment]
@tomschr I discussed it on matrix and it turned out to be a packaging bug, filed it over at https://bugzilla.opensuse.org/show_bug.cgi?id=1229161
