### ISSUE TITLE
Cache files do not contain document titles

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#31]
TO THE ATTN of @svenseeberg:
It seems that only the titles for subdeliverables are now generated into the document cache files.

In the following cases we do not have titles now:
* DC definition without subdeliverables
* General title for DC definition with subdeliverables (I'll admit, I only thought of that right now but might be useful
* Random other cases apparently as with the result document below which does not have titles for the ID of book.admin

```
<docset>
 <document dc="DC-SLES-all" format="html">
  <commit>68630ae08fa0edd75696d59493bdeb7fbf535971</commit>
  <path>en-us/sles/15ga/html/SLES-all/</path>
  <path>en-us/sles/15ga/html/SLES-all/</path>
  <subdeliverable id="book.admin" />
  <subdeliverable id="book.gnomeuser">GNOME User Guide</subdeliverable>
 </document>
</docset>
```

(NB: there are also two "path" tags in this file.)

**Comment by svenseeberg** [comment]
So this was a config error and we had insufficient logging to detect it. Fixed in #34
