### ISSUE TITLE
Support --internal-mode parameter of docserv-buildoverview

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#32]
TO THE IMMEDIATE ATTN of @svenseeberg:
We're using the same config file for multiple target servers, but we are still generating different slightly different overview pages for those target servers.

The RNC supports the "lifecycle" attribute for docsets which allows us to toggle docset visibility and the label "beta". However, I'd like to make visibility of content marked lifecycle="unpublished" dependent on it being public/internal.

Would it make sense to you to add `publishing_mode=internal`/`publishing_mode=public` to the target definitions in the INI file? You could then hand docserv-buildoverview the parameter --internal-mode in addition if were building for internal use.

**Comment by svenseeberg** [comment]
The immediate attention of @svenseeberg was raised.
