### ISSUE TITLE
apache redirects & aliases

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#42]
there will be lots of cases where the suse homepage supports a specific locale but our documentation is not translated into that language. in those cases, we probably want to redirect back to the /en-us/ page.
but how do we do that? (using empty html pages sounds like a crap solution but would not really be functional regression compared to the current suse.com/doc.)

**Comment by svenseeberg** [comment]
We could generate an apach2 configuration file that contains all the redirects.

**Comment by sknorr** [comment]
these are two different cases which we should treat differently:

1. renamed product -> manual configuration in XML -> redirect
2. unsupported language -> automatically generated (list of available languages v/ list of languages supported by server) -> alias

[summarizing a discussion from this afternoon.]

**Comment by sknorr** [comment]
replaced by #112 & #113
