### ISSUE TITLE
Allow -h/--help for docserv-stitch

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docserv#66]
## Problem

The script `bin/docserv-stitch` doesn't know the `-h` or `--help` option.

## Expected behavior

It would be really nice, if the script recognizes the `-h` or `--help` option :wink:  Thanks! :+1:

**Comment by sknorr** [comment]
Have you even tried the script? This is supported.

**Comment by tomschr** [comment]
After asking Stefan, you need to source `dev-mode.sh`. before you can run the script.

Ok, yes, you need to know this or read the README. Still, IMHO, this should give the user at least a friendly warning to source `dev-mode.sh`.  :)
