### ISSUE TITLE
dockerhub image update requests

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#8]
we are asking dockerhub for image updates with each build. that may not be ideal:

* if there actually is an update, we will ask for it up to 8 times (because threads) which may introduce interesting behavior
* if docker hub has any sort of rate limiting, we're probably up against that wall

on d2d_runner side, we can trivially add -u=1 to the command line, but we need a replacement behavior both for updates and for the initial download of the image. (as the image does not come with the rpm, things will fail hard if there is no image.)

**Comment by svenseeberg** [comment]
Done.
