### ISSUE TITLE
should config JSON really be written to /etc?

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#81]
right now, docserv.py's save_state() writes a JSON version of the config INI to the directory where the config INI itself is also stored (i.e. `/etc/docserv`). i am wondering if that is wise, or if the daemon should leave this directory untouched instead (to make sure no user data is ever overwritten) and write its JSON to yet another `/tmp/...` dir.

**Comment by svenseeberg** [comment]
No, save_state does not write the content of the ini file but the content of the REST API. This contains all the last build commit hashes, documents, etc.

**Comment by sknorr** [comment]
ah ... should have looked more closely. i like the `var/cache/docserv` option.
