### ISSUE TITLE
make /tmp cleanup work properly

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#82]
docserv² currently carpet-bombs my /tmp dir with random-sounding subdirs ... it does not seem to properly clean up after itself.

**Comment by svenseeberg** [comment]
I'd suggest to add a cron job for now. Something like
```find /tmp/docserv-* -mtime +7 -exec echo removing {}: older than 7 days \; -delete```

**Comment by sknorr** [comment]
This has been fixed a long time ago. We only have issues with this when Ds2 crashes/needs to be stopped while processing files -- and in those cases, it's expected (and possibly even helpful) that it can't delete temporary files.
