### ISSUE TITLE
metadata cache files need to properly id the source documents

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#93]
within our document-metadata cache files, we need a way to uniquely identify the documents we want, otherwise, it just becomes super-hard to create proper overview pages where html+other formats are grouped.
this means we need to look at the actual dc files, strip everything except MAIN+ROOTID+PROF...+STYLEROOT, then remove spaces/quotes, sort lines, then hash and put that into cache file. the ROOTID line needs to be changed for subdeliverables.

**Comment by svenseeberg** [comment]
How to do it? I'd be willing to contribute a fix here.

**Comment by sknorr** [comment]
Don't worry -- I have the biggest part of an implementation in portwinestain, we just need to plug that in.
